<?php
/**
 * Registry of all 200 tools (slug, name, category, styling).
 *
 * @package toolverse
 */

if (!defined('ABSPATH')) {
	exit;
}

$toolverse_cat = static function (string $category, string $category_slug, string $icon, string $c1, string $c2, array $pairs): array {
	$out = [];
	foreach ($pairs as $p) {
		$out[] = [
			'slug'            => $p[0],
			'name'            => $p[1],
			'category'        => $category,
			'category_slug'   => $category_slug,
			'icon'            => $icon,
			'color_start'     => $c1,
			'color_end'       => $c2,
			'description'     => sprintf(
				/* translators: %s: tool name */
				__('Free online %s — fast, private, and easy to use.', 'toolverse'),
				strtolower($p[1])
			),
		];
	}
	return $out;
};

return array_merge(
	$toolverse_cat(
		'PDF Tools',
		'pdf-tools',
		'📄',
		'#E1785B',
		'#F0A088',
		[
			['pdf-to-word', 'PDF to Word Converter'],
			['pdf-to-excel', 'PDF to Excel Converter'],
			['pdf-to-ppt', 'PDF to PowerPoint'],
			['pdf-to-jpg', 'PDF to JPG/PNG Images'],
			['pdf-to-html', 'PDF to HTML'],
			['pdf-to-text', 'PDF to Plain Text'],
			['word-to-pdf', 'Word to PDF'],
			['excel-to-pdf', 'Excel to PDF'],
			['ppt-to-pdf', 'PowerPoint to PDF'],
			['jpg-to-pdf', 'JPG/Image to PDF'],
			['html-to-pdf', 'HTML to PDF'],
			['merge-pdf', 'Merge PDFs'],
			['split-pdf', 'Split PDF'],
			['compress-pdf', 'Compress PDF'],
			['rotate-pdf', 'Rotate PDF Pages'],
			['unlock-pdf', 'Unlock PDF (remove password)'],
			['protect-pdf', 'Password Protect PDF'],
			['sign-pdf', 'e-Sign PDF'],
			['edit-pdf', 'Edit PDF Text'],
			['watermark-pdf', 'Add Watermark to PDF'],
			['page-numbers-pdf', 'Add Page Numbers'],
			['ocr-pdf', 'OCR (Scan to Text)'],
			['redact-pdf', 'Redact PDF'],
			['pdf-metadata', 'Edit PDF Metadata'],
			['compare-pdf', 'Compare Two PDFs'],
		]
	),
	$toolverse_cat(
		'Image Tools',
		'image-tools',
		'🖼️',
		'#B47CFD',
		'#9254EB',
		[
			['image-compressor', 'Image Compressor'],
			['image-resizer', 'Image Resizer'],
			['image-cropper', 'Image Cropper'],
			['image-converter', 'Image Format Converter'],
			['webp-converter', 'WebP Converter'],
			['jpg-to-png', 'JPG to PNG'],
			['png-to-jpg', 'PNG to JPG'],
			['png-to-svg', 'PNG to SVG'],
			['svg-to-png', 'SVG to PNG'],
			['gif-maker', 'GIF Maker/Creator'],
			['gif-to-mp4', 'GIF to MP4'],
			['image-editor', 'Online Image Editor'],
			['bg-remover', 'Background Remover (AI)'],
			['face-swap', 'AI Face Swapper'],
			['image-enhancer', 'AI Image Enhancer/Upscaler'],
			['photo-colorizer', 'Black & White Photo Colorizer'],
			['image-to-text', 'Image to Text (OCR)'],
			['qr-generator', 'QR Code Generator'],
			['qr-scanner', 'QR Code Scanner'],
			['barcode-generator', 'Barcode Generator'],
			['screenshot-tool', 'Screenshot to PDF'],
			['favicon-generator', 'Favicon Generator'],
			['logo-maker', 'Logo Maker'],
			['meme-generator', 'Meme Generator'],
			['color-picker', 'Color Picker from Image'],
			['image-color-palette', 'Image Color Palette Extractor'],
			['blur-image', 'Blur Image/Face'],
			['add-text-image', 'Add Text to Image'],
			['photo-filters', 'Apply Photo Filters'],
			['collage-maker', 'Photo Collage Maker'],
		]
	),
	$toolverse_cat(
		'Text Tools',
		'text-tools',
		'📝',
		'#A7938E',
		'#C9B8B2',
		[
			['word-counter', 'Word & Character Counter'],
			['text-case-converter', 'Text Case Converter'],
			['text-reverser', 'Text Reverser'],
			['duplicate-remover', 'Remove Duplicate Lines'],
			['text-sorter', 'Sort Lines Alphabetically'],
			['text-diff', 'Text Diff Checker'],
			['find-replace', 'Find and Replace Text'],
			['text-cleaner', 'Text Cleaner'],
			['lorem-ipsum', 'Lorem Ipsum Generator'],
			['text-to-speech', 'Text to Speech'],
			['speech-to-text', 'Speech to Text'],
			['grammar-checker', 'Grammar & Spell Checker'],
			['plagiarism-checker', 'Plagiarism Checker'],
			['ai-detector', 'AI Content Detector'],
			['paraphraser', 'AI Paraphraser/Rewriter'],
			['summarizer', 'AI Text Summarizer'],
			['translator', 'Text Translator'],
			['text-to-binary', 'Text to Binary'],
			['binary-to-text', 'Binary to Text'],
			['text-to-morse', 'Text to Morse Code'],
			['morse-to-text', 'Morse Code to Text'],
			['text-extractor', 'Extract Text from File'],
			['citation-generator', 'Citation/Bibliography Generator'],
			['essay-checker', 'Essay Grader'],
			['readability-score', 'Readability Score Analyzer'],
		]
	),
	$toolverse_cat(
		'SEO Tools',
		'seo-tools',
		'🔍',
		'#E1785B',
		'#B47CFD',
		[
			['keyword-research', 'Keyword Research Tool'],
			['meta-tag-generator', 'Meta Tag Generator'],
			['sitemap-generator', 'XML Sitemap Generator'],
			['robots-txt', 'Robots.txt Generator'],
			['page-speed-test', 'Page Speed Analyzer'],
			['seo-analyzer', 'On-Page SEO Analyzer'],
			['backlink-checker', 'Backlink Checker'],
			['domain-authority', 'Domain Authority Checker'],
			['broken-link-checker', 'Broken Link Checker'],
			['schema-generator', 'Schema Markup Generator'],
			['og-tag-generator', 'Open Graph Tag Generator'],
			['canonical-checker', 'Canonical Tag Checker'],
			['redirect-checker', 'Redirect Chain Checker'],
			['serp-preview', 'SERP Preview Tool'],
			['keyword-density', 'Keyword Density Checker'],
			['anchor-text-analyzer', 'Anchor Text Analyzer'],
			['ssl-checker', 'SSL Certificate Checker'],
			['http-headers', 'HTTP Headers Checker'],
			['mobile-friendly', 'Mobile-Friendly Tester'],
			['core-web-vitals', 'Core Web Vitals Checker'],
		]
	),
	$toolverse_cat(
		'Developer Tools',
		'developer-tools',
		'💻',
		'#7B9ECC',
		'#B47CFD',
		[
			['json-formatter', 'JSON Formatter & Validator'],
			['json-to-csv', 'JSON to CSV Converter'],
			['csv-to-json', 'CSV to JSON Converter'],
			['xml-formatter', 'XML Formatter & Validator'],
			['html-formatter', 'HTML Formatter/Beautifier'],
			['css-formatter', 'CSS Formatter/Beautifier'],
			['js-formatter', 'JavaScript Formatter/Minifier'],
			['html-minifier', 'HTML Minifier'],
			['css-minifier', 'CSS Minifier'],
			['js-minifier', 'JavaScript Minifier'],
			['sql-formatter', 'SQL Formatter'],
			['markdown-editor', 'Markdown Editor & Preview'],
			['regex-tester', 'Regex Tester & Debugger'],
			['jwt-decoder', 'JWT Token Decoder'],
			['base64-encoder', 'Base64 Encoder/Decoder'],
			['url-encoder', 'URL Encoder/Decoder'],
			['html-encoder', 'HTML Entity Encoder/Decoder'],
			['hash-generator', 'Hash Generator'],
			['uuid-generator', 'UUID/GUID Generator'],
			['password-generator', 'Strong Password Generator'],
			['cron-expression', 'Cron Expression Generator'],
			['htaccess-generator', '.htaccess Generator'],
			['nginx-config', 'Nginx Config Generator'],
			['color-converter', 'Color Code Converter'],
			['css-gradient', 'CSS Gradient Generator'],
			['css-box-shadow', 'CSS Box Shadow Generator'],
			['css-animation', 'CSS Animation Generator'],
			['api-tester', 'REST API Tester'],
			['ip-lookup', 'IP Address Lookup'],
			['port-scanner', 'Port Scanner (limited)'],
		]
	),
	$toolverse_cat(
		'Converter Tools',
		'converter-tools',
		'🔄',
		'#5EB89A',
		'#E1785B',
		[
			['unit-converter', 'Unit Converter'],
			['currency-converter', 'Currency Converter'],
			['temperature-conv', 'Temperature Converter'],
			['length-converter', 'Length Unit Converter'],
			['weight-converter', 'Weight/Mass Converter'],
			['area-converter', 'Area Converter'],
			['volume-converter', 'Volume Converter'],
			['speed-converter', 'Speed Converter'],
			['time-converter', 'Time Zone Converter'],
			['number-converter', 'Number System Converter'],
			['roman-numeral', 'Roman Numeral Converter'],
			['age-calculator', 'Age Calculator'],
			['date-calculator', 'Date Difference Calculator'],
			['bmi-calculator', 'BMI Calculator'],
			['loan-calculator', 'Loan/EMI Calculator'],
			['discount-calculator', 'Discount Calculator'],
			['percentage-calc', 'Percentage Calculator'],
			['tip-calculator', 'Tip Calculator'],
			['fuel-calculator', 'Fuel Cost Calculator'],
			['calorie-calculator', 'Calorie Calculator'],
		]
	),
	$toolverse_cat(
		'AI Tools',
		'ai-tools',
		'🤖',
		'#B47CFD',
		'#E1785B',
		[
			['ai-writer', 'AI Content Writer'],
			['ai-blog-writer', 'AI Blog Post Generator'],
			['ai-email-writer', 'AI Email Writer'],
			['ai-resume-writer', 'AI Resume Builder'],
			['ai-cover-letter', 'AI Cover Letter Generator'],
			['ai-product-desc', 'AI Product Description Writer'],
			['ai-social-caption', 'AI Social Media Caption Generator'],
			['ai-hashtag-gen', 'AI Hashtag Generator'],
			['ai-title-gen', 'AI Title & Headline Generator'],
			['ai-idea-gen', 'AI Business Idea Generator'],
			['ai-code-gen', 'AI Code Generator'],
			['ai-code-explain', 'AI Code Explainer'],
			['ai-code-review', 'AI Code Reviewer'],
			['ai-sql-gen', 'AI SQL Query Generator'],
			['ai-image-gen', 'AI Image Generator'],
			['ai-logo-gen', 'AI Logo Generator'],
			['ai-chatbot', 'Custom AI Chatbot'],
			['ai-quiz-gen', 'AI Quiz Generator'],
			['ai-lesson-planner', 'AI Lesson Planner'],
			['ai-story-gen', 'AI Story Generator'],
		]
	),
	$toolverse_cat(
		'Utility Tools',
		'utility-tools',
		'🛠️',
		'#A7938E',
		'#B47CFD',
		[
			['url-shortener', 'URL Shortener'],
			['url-expander', 'URL Expander'],
			['whois-lookup', 'WHOIS Domain Lookup'],
			['dns-lookup', 'DNS Lookup'],
			['ping-test', 'Website Ping Test'],
			['website-downcheck', 'Is Website Down Checker'],
			['google-cache', 'Google Cache Viewer'],
			['page-authority', 'Page Authority Checker'],
			['word-to-html', 'Word to HTML Converter'],
			['html-to-markdown', 'HTML to Markdown'],
			['epub-to-pdf', 'EPUB to PDF'],
			['ebook-converter', 'eBook Format Converter'],
			['invoice-generator', 'Invoice Generator'],
			['resume-builder', 'Resume/CV Builder'],
			['business-card', 'Business Card Designer'],
			['certificate-maker', 'Certificate Maker'],
			['signature-maker', 'Email/Digital Signature Maker'],
			['countdown-timer', 'Countdown Timer'],
			['stopwatch', 'Online Stopwatch'],
			['alarm-clock', 'Online Alarm Clock'],
			['random-generator', 'Random Number/String Generator'],
			['dice-roller', 'Virtual Dice Roller'],
			['coin-flip', 'Virtual Coin Flip'],
			['screen-recorder', 'Screen Recorder (browser)'],
			['webcam-test', 'Webcam Test'],
			['mic-test', 'Microphone Test'],
			['internet-speed', 'Internet Speed Test'],
			['battery-status', 'Battery Status Checker'],
			['screen-resolution', 'Screen Resolution Checker'],
			['browser-info', 'Browser Info Checker'],
		]
	)
);
